// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Schema definitions
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Block         *SchemaBlock           `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Schema) GetBlock() *SchemaBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

type SchemaBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    map[string]*Attribute  `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BlockTypes    map[string]*BlockType  `protobuf:"bytes,2,rep,name=block_types,json=blockTypes,proto3" json:"block_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaBlock) Reset() {
	*x = SchemaBlock{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaBlock) ProtoMessage() {}

func (x *SchemaBlock) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaBlock.ProtoReflect.Descriptor instead.
func (*SchemaBlock) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaBlock) GetAttributes() map[string]*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SchemaBlock) GetBlockTypes() map[string]*BlockType {
	if x != nil {
		return x.BlockTypes
	}
	return nil
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Optional      bool                   `protobuf:"varint,4,opt,name=optional,proto3" json:"optional,omitempty"`
	Computed      bool                   `protobuf:"varint,5,opt,name=computed,proto3" json:"computed,omitempty"`
	Sensitive     bool                   `protobuf:"varint,6,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Attribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Attribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Attribute) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Attribute) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *Attribute) GetComputed() bool {
	if x != nil {
		return x.Computed
	}
	return false
}

func (x *Attribute) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

type BlockType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestingMode   string                 `protobuf:"bytes,1,opt,name=nesting_mode,json=nestingMode,proto3" json:"nesting_mode,omitempty"`
	Block         *SchemaBlock           `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	MinItems      int64                  `protobuf:"varint,3,opt,name=min_items,json=minItems,proto3" json:"min_items,omitempty"`
	MaxItems      int64                  `protobuf:"varint,4,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockType) Reset() {
	*x = BlockType{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockType) ProtoMessage() {}

func (x *BlockType) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockType.ProtoReflect.Descriptor instead.
func (*BlockType) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *BlockType) GetNestingMode() string {
	if x != nil {
		return x.NestingMode
	}
	return ""
}

func (x *BlockType) GetBlock() *SchemaBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockType) GetMinItems() int64 {
	if x != nil {
		return x.MinItems
	}
	return 0
}

func (x *BlockType) GetMaxItems() int64 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

// Request/Response messages
type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

type GetSchemaResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Provider          *Schema                `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ResourceSchemas   map[string]*Schema     `protobuf:"bytes,2,rep,name=resource_schemas,json=resourceSchemas,proto3" json:"resource_schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DataSourceSchemas map[string]*Schema     `protobuf:"bytes,3,rep,name=data_source_schemas,json=dataSourceSchemas,proto3" json:"data_source_schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Diagnostics       []*Diagnostic          `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *GetSchemaResponse) GetProvider() *Schema {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetSchemaResponse) GetResourceSchemas() map[string]*Schema {
	if x != nil {
		return x.ResourceSchemas
	}
	return nil
}

func (x *GetSchemaResponse) GetDataSourceSchemas() map[string]*Schema {
	if x != nil {
		return x.DataSourceSchemas
	}
	return nil
}

func (x *GetSchemaResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ConfigureRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TerraformVersion string                 `protobuf:"bytes,1,opt,name=terraform_version,json=terraformVersion,proto3" json:"terraform_version,omitempty"`
	Config           *DynamicValue          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigureRequest) GetTerraformVersion() string {
	if x != nil {
		return x.TerraformVersion
	}
	return ""
}

func (x *ConfigureRequest) GetConfig() *DynamicValue {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type PlanResourceChangeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TypeName         string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	PriorState       *DynamicValue          `protobuf:"bytes,2,opt,name=prior_state,json=priorState,proto3" json:"prior_state,omitempty"`
	ProposedNewState *DynamicValue          `protobuf:"bytes,3,opt,name=proposed_new_state,json=proposedNewState,proto3" json:"proposed_new_state,omitempty"`
	Config           *DynamicValue          `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	PriorPrivate     []byte                 `protobuf:"bytes,5,opt,name=prior_private,json=priorPrivate,proto3" json:"prior_private,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlanResourceChangeRequest) Reset() {
	*x = PlanResourceChangeRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResourceChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResourceChangeRequest) ProtoMessage() {}

func (x *PlanResourceChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResourceChangeRequest.ProtoReflect.Descriptor instead.
func (*PlanResourceChangeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PlanResourceChangeRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *PlanResourceChangeRequest) GetPriorState() *DynamicValue {
	if x != nil {
		return x.PriorState
	}
	return nil
}

func (x *PlanResourceChangeRequest) GetProposedNewState() *DynamicValue {
	if x != nil {
		return x.ProposedNewState
	}
	return nil
}

func (x *PlanResourceChangeRequest) GetConfig() *DynamicValue {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PlanResourceChangeRequest) GetPriorPrivate() []byte {
	if x != nil {
		return x.PriorPrivate
	}
	return nil
}

type PlanResourceChangeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlannedState    *DynamicValue          `protobuf:"bytes,1,opt,name=planned_state,json=plannedState,proto3" json:"planned_state,omitempty"`
	RequiresReplace []string               `protobuf:"bytes,2,rep,name=requires_replace,json=requiresReplace,proto3" json:"requires_replace,omitempty"`
	PlannedPrivate  []byte                 `protobuf:"bytes,3,opt,name=planned_private,json=plannedPrivate,proto3" json:"planned_private,omitempty"`
	Diagnostics     []*Diagnostic          `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanResourceChangeResponse) Reset() {
	*x = PlanResourceChangeResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResourceChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResourceChangeResponse) ProtoMessage() {}

func (x *PlanResourceChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResourceChangeResponse.ProtoReflect.Descriptor instead.
func (*PlanResourceChangeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PlanResourceChangeResponse) GetPlannedState() *DynamicValue {
	if x != nil {
		return x.PlannedState
	}
	return nil
}

func (x *PlanResourceChangeResponse) GetRequiresReplace() []string {
	if x != nil {
		return x.RequiresReplace
	}
	return nil
}

func (x *PlanResourceChangeResponse) GetPlannedPrivate() []byte {
	if x != nil {
		return x.PlannedPrivate
	}
	return nil
}

func (x *PlanResourceChangeResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ApplyResourceChangeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TypeName       string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	PriorState     *DynamicValue          `protobuf:"bytes,2,opt,name=prior_state,json=priorState,proto3" json:"prior_state,omitempty"`
	PlannedState   *DynamicValue          `protobuf:"bytes,3,opt,name=planned_state,json=plannedState,proto3" json:"planned_state,omitempty"`
	Config         *DynamicValue          `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	PlannedPrivate []byte                 `protobuf:"bytes,5,opt,name=planned_private,json=plannedPrivate,proto3" json:"planned_private,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyResourceChangeRequest) Reset() {
	*x = ApplyResourceChangeRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourceChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourceChangeRequest) ProtoMessage() {}

func (x *ApplyResourceChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourceChangeRequest.ProtoReflect.Descriptor instead.
func (*ApplyResourceChangeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyResourceChangeRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ApplyResourceChangeRequest) GetPriorState() *DynamicValue {
	if x != nil {
		return x.PriorState
	}
	return nil
}

func (x *ApplyResourceChangeRequest) GetPlannedState() *DynamicValue {
	if x != nil {
		return x.PlannedState
	}
	return nil
}

func (x *ApplyResourceChangeRequest) GetConfig() *DynamicValue {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ApplyResourceChangeRequest) GetPlannedPrivate() []byte {
	if x != nil {
		return x.PlannedPrivate
	}
	return nil
}

type ApplyResourceChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      *DynamicValue          `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Private       []byte                 `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResourceChangeResponse) Reset() {
	*x = ApplyResourceChangeResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourceChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourceChangeResponse) ProtoMessage() {}

func (x *ApplyResourceChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourceChangeResponse.ProtoReflect.Descriptor instead.
func (*ApplyResourceChangeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyResourceChangeResponse) GetNewState() *DynamicValue {
	if x != nil {
		return x.NewState
	}
	return nil
}

func (x *ApplyResourceChangeResponse) GetPrivate() []byte {
	if x != nil {
		return x.Private
	}
	return nil
}

func (x *ApplyResourceChangeResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ReadResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	CurrentState  *DynamicValue          `protobuf:"bytes,2,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Private       []byte                 `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResourceRequest) Reset() {
	*x = ReadResourceRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceRequest) ProtoMessage() {}

func (x *ReadResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceRequest.ProtoReflect.Descriptor instead.
func (*ReadResourceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ReadResourceRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ReadResourceRequest) GetCurrentState() *DynamicValue {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *ReadResourceRequest) GetPrivate() []byte {
	if x != nil {
		return x.Private
	}
	return nil
}

type ReadResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      *DynamicValue          `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Private       []byte                 `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResourceResponse) Reset() {
	*x = ReadResourceResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceResponse) ProtoMessage() {}

func (x *ReadResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceResponse.ProtoReflect.Descriptor instead.
func (*ReadResourceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ReadResourceResponse) GetNewState() *DynamicValue {
	if x != nil {
		return x.NewState
	}
	return nil
}

func (x *ReadResourceResponse) GetPrivate() []byte {
	if x != nil {
		return x.Private
	}
	return nil
}

func (x *ReadResourceResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ImportResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResourceRequest) Reset() {
	*x = ImportResourceRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResourceRequest) ProtoMessage() {}

func (x *ImportResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResourceRequest.ProtoReflect.Descriptor instead.
func (*ImportResourceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ImportResourceRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ImportResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ImportResourceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ImportedResources []*ImportedResource    `protobuf:"bytes,1,rep,name=imported_resources,json=importedResources,proto3" json:"imported_resources,omitempty"`
	Diagnostics       []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ImportResourceResponse) Reset() {
	*x = ImportResourceResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResourceResponse) ProtoMessage() {}

func (x *ImportResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResourceResponse.ProtoReflect.Descriptor instead.
func (*ImportResourceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ImportResourceResponse) GetImportedResources() []*ImportedResource {
	if x != nil {
		return x.ImportedResources
	}
	return nil
}

func (x *ImportResourceResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ImportedResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	State         *DynamicValue          `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Private       []byte                 `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedResource) Reset() {
	*x = ImportedResource{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedResource) ProtoMessage() {}

func (x *ImportedResource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedResource.ProtoReflect.Descriptor instead.
func (*ImportedResource) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ImportedResource) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ImportedResource) GetState() *DynamicValue {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ImportedResource) GetPrivate() []byte {
	if x != nil {
		return x.Private
	}
	return nil
}

type ValidateResourceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Config        *DynamicValue          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResourceConfigRequest) Reset() {
	*x = ValidateResourceConfigRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResourceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResourceConfigRequest) ProtoMessage() {}

func (x *ValidateResourceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResourceConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateResourceConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateResourceConfigRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ValidateResourceConfigRequest) GetConfig() *DynamicValue {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateResourceConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResourceConfigResponse) Reset() {
	*x = ValidateResourceConfigResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResourceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResourceConfigResponse) ProtoMessage() {}

func (x *ValidateResourceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResourceConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateResourceConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateResourceConfigResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// Helper messages
type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *Diagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Diagnostic) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Diagnostic) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type DynamicValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // JSON-encoded value for flexibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicValue) Reset() {
	*x = DynamicValue{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicValue) ProtoMessage() {}

func (x *DynamicValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicValue.ProtoReflect.Descriptor instead.
func (*DynamicValue) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *DynamicValue) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_pkg_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/plugin.proto\x12\x06plugin\"M\n" +
	"\x06Schema\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12)\n" +
	"\x05block\x18\x02 \x01(\v2\x13.plugin.SchemaBlockR\x05block\"\xbc\x02\n" +
	"\vSchemaBlock\x12C\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2#.plugin.SchemaBlock.AttributesEntryR\n" +
	"attributes\x12D\n" +
	"\vblock_types\x18\x02 \x03(\v2#.plugin.SchemaBlock.BlockTypesEntryR\n" +
	"blockTypes\x1aP\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.plugin.AttributeR\x05value:\x028\x01\x1aP\n" +
	"\x0fBlockTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.plugin.BlockTypeR\x05value:\x028\x01\"\xb3\x01\n" +
	"\tAttribute\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x1a\n" +
	"\boptional\x18\x04 \x01(\bR\boptional\x12\x1a\n" +
	"\bcomputed\x18\x05 \x01(\bR\bcomputed\x12\x1c\n" +
	"\tsensitive\x18\x06 \x01(\bR\tsensitive\"\x93\x01\n" +
	"\tBlockType\x12!\n" +
	"\fnesting_mode\x18\x01 \x01(\tR\vnestingMode\x12)\n" +
	"\x05block\x18\x02 \x01(\v2\x13.plugin.SchemaBlockR\x05block\x12\x1b\n" +
	"\tmin_items\x18\x03 \x01(\x03R\bminItems\x12\x1b\n" +
	"\tmax_items\x18\x04 \x01(\x03R\bmaxItems\"\x12\n" +
	"\x10GetSchemaRequest\"\xdc\x03\n" +
	"\x11GetSchemaResponse\x12*\n" +
	"\bprovider\x18\x01 \x01(\v2\x0e.plugin.SchemaR\bprovider\x12Y\n" +
	"\x10resource_schemas\x18\x02 \x03(\v2..plugin.GetSchemaResponse.ResourceSchemasEntryR\x0fresourceSchemas\x12`\n" +
	"\x13data_source_schemas\x18\x03 \x03(\v20.plugin.GetSchemaResponse.DataSourceSchemasEntryR\x11dataSourceSchemas\x124\n" +
	"\vdiagnostics\x18\x04 \x03(\v2\x12.plugin.DiagnosticR\vdiagnostics\x1aR\n" +
	"\x14ResourceSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.plugin.SchemaR\x05value:\x028\x01\x1aT\n" +
	"\x16DataSourceSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.plugin.SchemaR\x05value:\x028\x01\"m\n" +
	"\x10ConfigureRequest\x12+\n" +
	"\x11terraform_version\x18\x01 \x01(\tR\x10terraformVersion\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.plugin.DynamicValueR\x06config\"I\n" +
	"\x11ConfigureResponse\x124\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x12.plugin.DiagnosticR\vdiagnostics\"\x86\x02\n" +
	"\x19PlanResourceChangeRequest\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x125\n" +
	"\vprior_state\x18\x02 \x01(\v2\x14.plugin.DynamicValueR\n" +
	"priorState\x12B\n" +
	"\x12proposed_new_state\x18\x03 \x01(\v2\x14.plugin.DynamicValueR\x10proposedNewState\x12,\n" +
	"\x06config\x18\x04 \x01(\v2\x14.plugin.DynamicValueR\x06config\x12#\n" +
	"\rprior_private\x18\x05 \x01(\fR\fpriorPrivate\"\xe1\x01\n" +
	"\x1aPlanResourceChangeResponse\x129\n" +
	"\rplanned_state\x18\x01 \x01(\v2\x14.plugin.DynamicValueR\fplannedState\x12)\n" +
	"\x10requires_replace\x18\x02 \x03(\tR\x0frequiresReplace\x12'\n" +
	"\x0fplanned_private\x18\x03 \x01(\fR\x0eplannedPrivate\x124\n" +
	"\vdiagnostics\x18\x04 \x03(\v2\x12.plugin.DiagnosticR\vdiagnostics\"\x82\x02\n" +
	"\x1aApplyResourceChangeRequest\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x125\n" +
	"\vprior_state\x18\x02 \x01(\v2\x14.plugin.DynamicValueR\n" +
	"priorState\x129\n" +
	"\rplanned_state\x18\x03 \x01(\v2\x14.plugin.DynamicValueR\fplannedState\x12,\n" +
	"\x06config\x18\x04 \x01(\v2\x14.plugin.DynamicValueR\x06config\x12'\n" +
	"\x0fplanned_private\x18\x05 \x01(\fR\x0eplannedPrivate\"\xa0\x01\n" +
	"\x1bApplyResourceChangeResponse\x121\n" +
	"\tnew_state\x18\x01 \x01(\v2\x14.plugin.DynamicValueR\bnewState\x12\x18\n" +
	"\aprivate\x18\x02 \x01(\fR\aprivate\x124\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x12.plugin.DiagnosticR\vdiagnostics\"\x87\x01\n" +
	"\x13ReadResourceRequest\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x129\n" +
	"\rcurrent_state\x18\x02 \x01(\v2\x14.plugin.DynamicValueR\fcurrentState\x12\x18\n" +
	"\aprivate\x18\x03 \x01(\fR\aprivate\"\x99\x01\n" +
	"\x14ReadResourceResponse\x121\n" +
	"\tnew_state\x18\x01 \x01(\v2\x14.plugin.DynamicValueR\bnewState\x12\x18\n" +
	"\aprivate\x18\x02 \x01(\fR\aprivate\x124\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x12.plugin.DiagnosticR\vdiagnostics\"D\n" +
	"\x15ImportResourceRequest\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x97\x01\n" +
	"\x16ImportResourceResponse\x12G\n" +
	"\x12imported_resources\x18\x01 \x03(\v2\x18.plugin.ImportedResourceR\x11importedResources\x124\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x12.plugin.DiagnosticR\vdiagnostics\"u\n" +
	"\x10ImportedResource\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12*\n" +
	"\x05state\x18\x02 \x01(\v2\x14.plugin.DynamicValueR\x05state\x12\x18\n" +
	"\aprivate\x18\x03 \x01(\fR\aprivate\"j\n" +
	"\x1dValidateResourceConfigRequest\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.plugin.DynamicValueR\x06config\"V\n" +
	"\x1eValidateResourceConfigResponse\x124\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x12.plugin.DiagnosticR\vdiagnostics\"Z\n" +
	"\n" +
	"Diagnostic\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\"\n" +
	"\fDynamicValue\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json2\xd0\x04\n" +
	"\bProvider\x12@\n" +
	"\tGetSchema\x12\x18.plugin.GetSchemaRequest\x1a\x19.plugin.GetSchemaResponse\x12@\n" +
	"\tConfigure\x12\x18.plugin.ConfigureRequest\x1a\x19.plugin.ConfigureResponse\x12[\n" +
	"\x12PlanResourceChange\x12!.plugin.PlanResourceChangeRequest\x1a\".plugin.PlanResourceChangeResponse\x12^\n" +
	"\x13ApplyResourceChange\x12\".plugin.ApplyResourceChangeRequest\x1a#.plugin.ApplyResourceChangeResponse\x12I\n" +
	"\fReadResource\x12\x1b.plugin.ReadResourceRequest\x1a\x1c.plugin.ReadResourceResponse\x12O\n" +
	"\x0eImportResource\x12\x1d.plugin.ImportResourceRequest\x1a\x1e.plugin.ImportResourceResponse\x12g\n" +
	"\x16ValidateResourceConfig\x12%.plugin.ValidateResourceConfigRequest\x1a&.plugin.ValidateResourceConfigResponseB)Z'github.com/tblang/core/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pkg_plugin_proto_plugin_proto_goTypes = []any{
	(*Schema)(nil),                         // 0: plugin.Schema
	(*SchemaBlock)(nil),                    // 1: plugin.SchemaBlock
	(*Attribute)(nil),                      // 2: plugin.Attribute
	(*BlockType)(nil),                      // 3: plugin.BlockType
	(*GetSchemaRequest)(nil),               // 4: plugin.GetSchemaRequest
	(*GetSchemaResponse)(nil),              // 5: plugin.GetSchemaResponse
	(*ConfigureRequest)(nil),               // 6: plugin.ConfigureRequest
	(*ConfigureResponse)(nil),              // 7: plugin.ConfigureResponse
	(*PlanResourceChangeRequest)(nil),      // 8: plugin.PlanResourceChangeRequest
	(*PlanResourceChangeResponse)(nil),     // 9: plugin.PlanResourceChangeResponse
	(*ApplyResourceChangeRequest)(nil),     // 10: plugin.ApplyResourceChangeRequest
	(*ApplyResourceChangeResponse)(nil),    // 11: plugin.ApplyResourceChangeResponse
	(*ReadResourceRequest)(nil),            // 12: plugin.ReadResourceRequest
	(*ReadResourceResponse)(nil),           // 13: plugin.ReadResourceResponse
	(*ImportResourceRequest)(nil),          // 14: plugin.ImportResourceRequest
	(*ImportResourceResponse)(nil),         // 15: plugin.ImportResourceResponse
	(*ImportedResource)(nil),               // 16: plugin.ImportedResource
	(*ValidateResourceConfigRequest)(nil),  // 17: plugin.ValidateResourceConfigRequest
	(*ValidateResourceConfigResponse)(nil), // 18: plugin.ValidateResourceConfigResponse
	(*Diagnostic)(nil),                     // 19: plugin.Diagnostic
	(*DynamicValue)(nil),                   // 20: plugin.DynamicValue
	nil,                                    // 21: plugin.SchemaBlock.AttributesEntry
	nil,                                    // 22: plugin.SchemaBlock.BlockTypesEntry
	nil,                                    // 23: plugin.GetSchemaResponse.ResourceSchemasEntry
	nil,                                    // 24: plugin.GetSchemaResponse.DataSourceSchemasEntry
}
var file_pkg_plugin_proto_plugin_proto_depIdxs = []int32{
	1,  // 0: plugin.Schema.block:type_name -> plugin.SchemaBlock
	21, // 1: plugin.SchemaBlock.attributes:type_name -> plugin.SchemaBlock.AttributesEntry
	22, // 2: plugin.SchemaBlock.block_types:type_name -> plugin.SchemaBlock.BlockTypesEntry
	1,  // 3: plugin.BlockType.block:type_name -> plugin.SchemaBlock
	0,  // 4: plugin.GetSchemaResponse.provider:type_name -> plugin.Schema
	23, // 5: plugin.GetSchemaResponse.resource_schemas:type_name -> plugin.GetSchemaResponse.ResourceSchemasEntry
	24, // 6: plugin.GetSchemaResponse.data_source_schemas:type_name -> plugin.GetSchemaResponse.DataSourceSchemasEntry
	19, // 7: plugin.GetSchemaResponse.diagnostics:type_name -> plugin.Diagnostic
	20, // 8: plugin.ConfigureRequest.config:type_name -> plugin.DynamicValue
	19, // 9: plugin.ConfigureResponse.diagnostics:type_name -> plugin.Diagnostic
	20, // 10: plugin.PlanResourceChangeRequest.prior_state:type_name -> plugin.DynamicValue
	20, // 11: plugin.PlanResourceChangeRequest.proposed_new_state:type_name -> plugin.DynamicValue
	20, // 12: plugin.PlanResourceChangeRequest.config:type_name -> plugin.DynamicValue
	20, // 13: plugin.PlanResourceChangeResponse.planned_state:type_name -> plugin.DynamicValue
	19, // 14: plugin.PlanResourceChangeResponse.diagnostics:type_name -> plugin.Diagnostic
	20, // 15: plugin.ApplyResourceChangeRequest.prior_state:type_name -> plugin.DynamicValue
	20, // 16: plugin.ApplyResourceChangeRequest.planned_state:type_name -> plugin.DynamicValue
	20, // 17: plugin.ApplyResourceChangeRequest.config:type_name -> plugin.DynamicValue
	20, // 18: plugin.ApplyResourceChangeResponse.new_state:type_name -> plugin.DynamicValue
	19, // 19: plugin.ApplyResourceChangeResponse.diagnostics:type_name -> plugin.Diagnostic
	20, // 20: plugin.ReadResourceRequest.current_state:type_name -> plugin.DynamicValue
	20, // 21: plugin.ReadResourceResponse.new_state:type_name -> plugin.DynamicValue
	19, // 22: plugin.ReadResourceResponse.diagnostics:type_name -> plugin.Diagnostic
	16, // 23: plugin.ImportResourceResponse.imported_resources:type_name -> plugin.ImportedResource
	19, // 24: plugin.ImportResourceResponse.diagnostics:type_name -> plugin.Diagnostic
	20, // 25: plugin.ImportedResource.state:type_name -> plugin.DynamicValue
	20, // 26: plugin.ValidateResourceConfigRequest.config:type_name -> plugin.DynamicValue
	19, // 27: plugin.ValidateResourceConfigResponse.diagnostics:type_name -> plugin.Diagnostic
	2,  // 28: plugin.SchemaBlock.AttributesEntry.value:type_name -> plugin.Attribute
	3,  // 29: plugin.SchemaBlock.BlockTypesEntry.value:type_name -> plugin.BlockType
	0,  // 30: plugin.GetSchemaResponse.ResourceSchemasEntry.value:type_name -> plugin.Schema
	0,  // 31: plugin.GetSchemaResponse.DataSourceSchemasEntry.value:type_name -> plugin.Schema
	4,  // 32: plugin.Provider.GetSchema:input_type -> plugin.GetSchemaRequest
	6,  // 33: plugin.Provider.Configure:input_type -> plugin.ConfigureRequest
	8,  // 34: plugin.Provider.PlanResourceChange:input_type -> plugin.PlanResourceChangeRequest
	10, // 35: plugin.Provider.ApplyResourceChange:input_type -> plugin.ApplyResourceChangeRequest
	12, // 36: plugin.Provider.ReadResource:input_type -> plugin.ReadResourceRequest
	14, // 37: plugin.Provider.ImportResource:input_type -> plugin.ImportResourceRequest
	17, // 38: plugin.Provider.ValidateResourceConfig:input_type -> plugin.ValidateResourceConfigRequest
	5,  // 39: plugin.Provider.GetSchema:output_type -> plugin.GetSchemaResponse
	7,  // 40: plugin.Provider.Configure:output_type -> plugin.ConfigureResponse
	9,  // 41: plugin.Provider.PlanResourceChange:output_type -> plugin.PlanResourceChangeResponse
	11, // 42: plugin.Provider.ApplyResourceChange:output_type -> plugin.ApplyResourceChangeResponse
	13, // 43: plugin.Provider.ReadResource:output_type -> plugin.ReadResourceResponse
	15, // 44: plugin.Provider.ImportResource:output_type -> plugin.ImportResourceResponse
	18, // 45: plugin.Provider.ValidateResourceConfig:output_type -> plugin.ValidateResourceConfigResponse
	39, // [39:46] is the sub-list for method output_type
	32, // [32:39] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_proto_init() }
func file_pkg_plugin_proto_plugin_proto_init() {
	if File_pkg_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_proto = out.File
	file_pkg_plugin_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_proto_depIdxs = nil
}
